name: widgets
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.5
  dio: ^5.7.0
  html: ^0.15.4
  flutter_quill:
    git:
      url: https://github.com/imajoriri/flutter-quill.git
      ref: master
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
