name: model
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_crashlytics: ^4.1.0
  cloud_firestore: 5.3.0
  firebase_analytics: ^11.3.0
  firebase_vertexai: ^0.2.3
  firebase_app_check: ^0.3.0+5

  # Riverpod
  riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  riverpod_generator: ^3.0.0-dev.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
flutter:
