# 参考: https://zenn.dev/k_taro56/articles/how-to-build-ios-app-in-github-actions
# archiveはflutter build ipa --release --no-codesignで作成
name: Build

on:
  workflow_dispatch:

env:
  CERT_KEY: ${{ secrets.CERT_KEY }}
  APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
  APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
  APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
  APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
  APPLE_APP_ID: ${{ secrets.APPLE_APP_ID }}
  PLATFORM: IOS

jobs:
  build:
    name: Build
    runs-on: macos-latest
    defaults:
      run:
        working-directory: packages/mobile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - uses: kuhnroyal/flutter-fvm-config-action@v2
      #   with:
      #     setup: true
      #     cache: true

      # - name: flutter setup
      #   run: |
      #     dart pub global activate melos
      #     melos bootstrap --sdk-path=${{ env.FLUTTER_ROOT }}

      # - name: build ipa
      #   run: |
      #     flutter build ipa --release --no-codesign

      # - name: Create ExportOptions.plist
      #   run: |
      #     echo '${{ secrets.EXPORT_OPTIONS }}' > ExportOptions.plist

      # - name: Create Private Key
      #   run: |
      #     mkdir private_keys
      #     echo '${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}' > ./private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}.p8

      # - name: Export IPA
      #   run: |
      #     xcodebuild -exportArchive \
      #                -archivePath build/ios/archive/*.xcarchive \
      #                -exportOptionsPlist ExportOptions.plist \
      #                -exportPath app.ipa \
      #                -allowProvisioningUpdates \
      #                -authenticationKeyPath `pwd`/private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}.p8 \
      #                -authenticationKeyID ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }} \
      #                -authenticationKeyIssuerID ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}

      - name: Upload IPA to App Store Connect
        run: |
          xcrun altool --upload-app -f app.ipa/*.ipa \
                       -u ${{ secrets.APPLE_ID }} \
                       -p ${{ secrets.APP_SPECIFIC_PASSWORD }} \
                       --type ios
